### PR TITLE
Added Network Selector

### PR DESCRIPTION
**Pull request by farque65**
Screen Shot 2021-12-17 at 12 44 50 AM

### CODE REVIEW

**Comment by hansmrtn** [comment]
With the new refactor, there are conflicts that need to be resolved. 

Resolve and ping me! 👯

**Comment by farque65** [comment]
> With the new refactor, there are conflicts that need to be resolved.
> 
> Resolve and ping me! 👯

Created a new PR against the refactor branch https://github.com/farque65/pay.party/pull/1

**Comment by hansmrtn** [comment]
I edited it to resolve the conflicts. The visual implementation is commented out, because this merge will need to be adjusted to fit the current chakra based UI components. Will merge, and edit them.

**Review by hansmrtn — DISMISSED** [review]
Looks good, minus the UI adjustments needed! Probably need to re add some imports. I'll work on that!

**Pull request merged**
